module.exports = function(sequelize,DataTypes){
    var pemedical_doc = sequelize.define('pemedical_doc',{
        PATIENT_ID:{type:DataTypes.INTEGER(11), primaryKey:true},
        CAL_ID:DataTypes.INTEGER(11),
        header_check:DataTypes.STRING(2),
        part1_sec1_comment1:DataTypes.STRING(100),
        part1_sec1_comment2:DataTypes.STRING(100),
        part1_sec1_comment3:DataTypes.STRING(100),
        part1_sec1_comment4:DataTypes.STRING(100),
        part1_sec1_comment5:DataTypes.STRING(100),
        part1_sec1_comment6:DataTypes.STRING(100),
        part1_sec1_comment7:DataTypes.STRING(100),
        part1_sec1_comment8:DataTypes.STRING(100),
        part1_sec1_comment9:DataTypes.STRING(100),
        part1_sec1_comment10:DataTypes.STRING(100),
        part1_sec1_comment11:DataTypes.STRING(100),
        part1_sec1_comment12:DataTypes.STRING(100),
        part1_sec1_comment13:DataTypes.STRING(100),
        part1_sec1_comment14:DataTypes.STRING(100),
        part1_sec1_comment15:DataTypes.STRING(100),
        part1_sec1_comment16:DataTypes.STRING(100),
        part1_sec1_comment17:DataTypes.STRING(100),
        part1_sec1_comment18:DataTypes.STRING(100),
        part1_sec1_comment19:DataTypes.STRING(100),
        part1_sec1_comment20:DataTypes.STRING(100),
        part1_sec1_comment21:DataTypes.STRING(100),
        part1_sec1_comment22:DataTypes.STRING(100),
        part1_sec1_comment23:DataTypes.STRING(100),
        part1_sec1_comment24:DataTypes.STRING(100),
        part1_sec2_check1 :DataTypes.STRING(2),
        part1_sec2_check2:DataTypes.STRING(2),
        part1_sec2_check3:DataTypes.STRING(2),
        part1_sec2_check4:DataTypes.STRING(2),
        part1_sec2_check5:DataTypes.STRING(2),
        part1_sec2_check6:DataTypes.STRING(2),
        part1_sec2_check7:DataTypes.STRING(2),
        part1_sec2_check8:DataTypes.STRING(2),
        part1_sec2_check9:DataTypes.STRING(2),
        part1_sec2_check10:DataTypes.STRING(2),
        part1_sec2_check11:DataTypes.STRING(2),
        part1_sec2_check12:DataTypes.STRING(2),
        part1_sec2_check13:DataTypes.STRING(2),
        part1_sec2_check14:DataTypes.STRING(2),
        part1_sec2_check15:DataTypes.STRING(2),
        part1_sec2_check16:DataTypes.STRING(2),
        part1_sec2_check17:DataTypes.STRING(2),
        part1_sec2_check18:DataTypes.STRING(2),
        part1_sec2_check19:DataTypes.STRING(2),
        part1_sec2_check20:DataTypes.STRING(2),
        part1_sec2_check21:DataTypes.STRING(2),
        part1_sec2_check22:DataTypes.STRING(2),
        part1_sec2_check23:DataTypes.STRING(2),
        part1_sec2_check24:DataTypes.STRING(2),
        part1_sec2_check25:DataTypes.STRING(2),
        part1_sec2_check26:DataTypes.STRING(2),
        part1_sec2_check27:DataTypes.STRING(2),
        part1_sec2_check28:DataTypes.STRING(2),
        part1_sec2_check29:DataTypes.STRING(2),
        part1_sec2_check30:DataTypes.STRING(2),
        part1_sec2_check31:DataTypes.STRING(2),
        part1_sec2_check32:DataTypes.STRING(2),
        part1_sec2_check33:DataTypes.STRING(2),
        part1_sec2_check34:DataTypes.STRING(2),
        part1_sec2_check35:DataTypes.STRING(2),
        part1_sec2_check36:DataTypes.STRING(2),
        part1_sec2_check37:DataTypes.STRING(2),
        part1_sec2_check38:DataTypes.STRING(2),
        part1_sec2_check39:DataTypes.STRING(2),
        part1_sec2_check40:DataTypes.STRING(2),
        part1_sec2_check41:DataTypes.STRING(2),
        part1_sec2_check42:DataTypes.STRING(2),
        part1_sec2_check43:DataTypes.STRING(2),
        part1_sec2_check44:DataTypes.STRING(2),
        part1_sec2_check45:DataTypes.STRING(2),
        part1_sec2_check46:DataTypes.STRING(2),
        part1_sec2_comment1:DataTypes.STRING(100),
        part1_sec2_comment2:DataTypes.STRING(100),
        part1_sec3_comment1:DataTypes.STRING(100),
        part1_sec3_comment2:DataTypes.STRING(100),
        part1_sec3_comment3:DataTypes.STRING(100),
        part1_sec3_rate1:DataTypes.INTEGER(11),
        part1_sec3_rate2:DataTypes.INTEGER(11),
        part1_sec3_rate3:DataTypes.INTEGER(11),
        part1_sec3_check1:DataTypes.STRING(2),
        part1_sec4_value1:DataTypes.INTEGER(11),
        part1_sec4_value2:DataTypes.INTEGER(11),
        part1_sec4_value3:DataTypes.INTEGER(11),
        part1_sec4_value4:DataTypes.INTEGER(11),
        part1_sec4_check1:DataTypes.STRING(2),
        part1_sec4_check2:DataTypes.STRING(2),
        part1_sec4_check3:DataTypes.STRING(2),
        part1_sec4_check4:DataTypes.STRING(2),
        part1_sec4_check5:DataTypes.STRING(2),
        part1_sec4_check6:DataTypes.STRING(2),
        part1_sec4_check7:DataTypes.STRING(2),
        part1_sec5_check1 :DataTypes.STRING(2),
        part1_sec5_check2 :DataTypes.STRING(2),
        part1_sec5_check3 :DataTypes.STRING(2),
        part1_sec5_check4 :DataTypes.STRING(2),
        part1_sec5_check5 :DataTypes.STRING(2),
        part1_sec5_check6 :DataTypes.STRING(2),
        part1_sec5_check7 :DataTypes.STRING(2),
        part1_sec5_check8 :DataTypes.STRING(2),
        part1_sec5_check9 :DataTypes.STRING(2),
        part1_sec5_check10 :DataTypes.STRING(2),
        part1_sec5_check11 :DataTypes.STRING(2),
        part1_sec5_check12 :DataTypes.STRING(2),
        part1_sec5_check13 :DataTypes.STRING(2),
        part1_sec5_check14 :DataTypes.STRING(2),
        part1_sec5_check15 :DataTypes.STRING(2),
        part1_sec5_check16 :DataTypes.STRING(2),
        part1_sec5_check17 :DataTypes.STRING(2),
        part1_sec5_check18 :DataTypes.STRING(2),
        part1_sec5_check19 :DataTypes.STRING(2),
        part1_sec5_check20 :DataTypes.STRING(2),
        part1_sec5_check21 :DataTypes.STRING(2),
        part1_sec5_check22 :DataTypes.STRING(2),
        part1_sec5_comment1:DataTypes.STRING(100),
        part1_sec5_comment2:DataTypes.STRING(100),
        part1_sec6_check1  :DataTypes.STRING(2),
        part1_sec6_check2  :DataTypes.STRING(2),
        part1_sec6_check3  :DataTypes.STRING(2),
        part1_sec6_check4  :DataTypes.STRING(2),
        part1_sec6_check5  :DataTypes.STRING(2),
        part1_sec6_check6  :DataTypes.STRING(2),
        part1_sec6_check7  :DataTypes.STRING(2),
        part1_sec6_comment1:DataTypes.STRING(100),
        part1_sec6_comment2:DataTypes.STRING(100),
        part1_sec7_check1:DataTypes.STRING(2),
        part1_sec7_check2:DataTypes.STRING(2),
        part1_sec7_comment1:DataTypes.STRING(100),
        part2_sec1_value1:DataTypes.INTEGER(11),
        part2_sec1_value2:DataTypes.INTEGER(11),
        part2_sec1_rate1:DataTypes.STRING(2),
        part2_sec2_value1:DataTypes.INTEGER(11),
        part2_sec2_value2:DataTypes.INTEGER(11),
        part2_sec2_value3:DataTypes.INTEGER(11),
        part2_sec2_rate1:DataTypes.STRING(2),
        part2_sec2_rate2:DataTypes.STRING(2),
        part2_sec2_rate3:DataTypes.STRING(2),
        part2_sec2_rate4:DataTypes.STRING(2),
        part2_sec2_rate5:DataTypes.STRING(2),
        part2_sec3_rate1:DataTypes.STRING(2),
        part2_sec4_rate1:DataTypes.STRING(2),
        part2_sec4_rate2:DataTypes.STRING(2),
        part2_sec5_value1:DataTypes.INTEGER(11),
        part2_sec5_value2:DataTypes.INTEGER(11),
        part2_sec5_value3:DataTypes.INTEGER(11),
        part2_sec5_value4:DataTypes.INTEGER(11),
        part2_sec5_value5:DataTypes.INTEGER(11),
        part2_sec5_value6:DataTypes.INTEGER(11),
        part2_sec5_value7:DataTypes.INTEGER(11),
        part2_sec5_value8:DataTypes.INTEGER(11),
        part2_sec5_rate1:DataTypes.STRING(2),
        part2_sec5_rate2:DataTypes.STRING(2),
        part2_sec5_rate3:DataTypes.STRING(2),
        part2_sec5_rate4:DataTypes.STRING(2),
        part2_sec5_rate5:DataTypes.STRING(2),
        part2_sec6_rate1:DataTypes.STRING(2),
        part2_sec6_rate2:DataTypes.STRING(2),
        part2_sec6_rate3:DataTypes.STRING(2),
        part2_sec6_rate4:DataTypes.STRING(2),
        part2_sec7_rate1:DataTypes.STRING(2),
        part2_sec7_rate2:DataTypes.STRING(2),
        part2_sec7_rate3:DataTypes.STRING(2),
        part2_sec7_rate4:DataTypes.STRING(2),
        part2_sec7_rate5:DataTypes.STRING(2),
        part2_sec8_rate1:DataTypes.STRING(2),
        part2_sec8_rate2:DataTypes.STRING(2),
        part2_sec8_rate3:DataTypes.STRING(2),
        part2_sec8_value1:DataTypes.STRING(100),
        part2_sec8_value2:DataTypes.STRING(100),
        part2_sec8_value3:DataTypes.STRING(100),
        part2_sec8_value4:DataTypes.STRING(2),
        part2_sec9_rate1:DataTypes.STRING(2),
        part2_sec9_rate2:DataTypes.STRING(2),
        part2_sec9_rate3:DataTypes.STRING(2),
        part2_sec9_rate4:DataTypes.STRING(2),
        part2_sec9_rate5:DataTypes.STRING(2),
        part2_sec9_rate6:DataTypes.STRING(2),
        part2_sec9_rate7:DataTypes.STRING(2),
        part2_sec9_rate8:DataTypes.STRING(2),
        part2_sec9_rate9:DataTypes.STRING(2),
        part2_sec9_rate10:DataTypes.STRING(2),
        part2_sec9_value1:DataTypes.STRING(2),
        part2_sec9_value2:DataTypes.STRING(2),
        part2_sec10_comment1:DataTypes.STRING(100),
        part2_sec10_rate1:DataTypes.STRING(2),
        part3_sec1_rate1:DataTypes.STRING(2),
        part3_sec2_value1:DataTypes.STRING(2),
        part3_sec2_value2:DataTypes.STRING(2),
        part3_sec2_value3:DataTypes.STRING(2),
        part3_sec2_value4:DataTypes.STRING(2),
        part3_sec2_rate1:DataTypes.STRING(2),
        part3_sec3_comment1:DataTypes.STRING(100),
        part3_sec3_value1:DataTypes.STRING(2),
        part3_sec3_value2:DataTypes.STRING(2),
        part3_sec3_value3:DataTypes.STRING(2),
        part3_sec3_value4:DataTypes.STRING(2),
        part3_sec4_rate1:DataTypes.INTEGER(11),
        part3_sec4_rate2:DataTypes.INTEGER(11),
        part3_sec4_rate3:DataTypes.INTEGER(11),
        part3_sec4_rate4:DataTypes.INTEGER(11),
        part3_sec4_value1:DataTypes.STRING(2),
        part3_sec4_comment1:DataTypes.STRING(100),
        part3_sec5_rate1:DataTypes.INTEGER(11),
        part3_sec5_rate2:DataTypes.INTEGER(11),
        part3_sec5_rate3:DataTypes.INTEGER(11),
        part3_sec5_rate4:DataTypes.INTEGER(11),
        part3_sec5_value1:DataTypes.STRING(2),
        part3_sec5_comment1:DataTypes.STRING(100),
        part3_sec6_rate1:DataTypes.INTEGER(11),
        part3_sec6_rate2:DataTypes.INTEGER(11),
        part3_sec6_rate3:DataTypes.INTEGER(11),
        part3_sec6_rate4:DataTypes.INTEGER(11),
        part3_sec6_value1:DataTypes.STRING(2),
        part3_sec6_comment1:DataTypes.STRING(100),
        part3_sec7_rate1:DataTypes.INTEGER(11),
        part3_sec7_rate2:DataTypes.INTEGER(11),
        part3_sec7_rate3:DataTypes.INTEGER(11),
        part3_sec7_rate4:DataTypes.INTEGER(11),
        part3_sec7_value1:DataTypes.STRING(2),
        part3_sec7_comment1:DataTypes.STRING(100),
        part4_sec3_value1:DataTypes.STRING(2),
        part4_sec3_value2:DataTypes.STRING(2),
        part4_sec3_value3:DataTypes.STRING(100),
        part5_sec1_value1:DataTypes.STRING(2),
        part5_sec2_value1:DataTypes.STRING(2),
        part5_sec2_value2:DataTypes.STRING(2),
        part5_sec2_value3:DataTypes.STRING(2),
        part5_sec2_value4:DataTypes.STRING(2),
        part5_sec2_value5:DataTypes.STRING(2),
        part5_sec2_value6:DataTypes.STRING(2),
        part5_sec2_value7:DataTypes.STRING(2),
        part5_sec2_value8:DataTypes.STRING(2),
        part5_sec2_value9:DataTypes.STRING(2),
        part5_sec2_value10:DataTypes.STRING(2),
        part5_sec2_value11:DataTypes.STRING(2),
        part5_sec2_value12:DataTypes.STRING(2),
        part5_sec2_value13:DataTypes.STRING(2),
        part5_sec3_value1:DataTypes.STRING(100),
        part6_result_img:DataTypes.TEXT,
        part7_sec1_value1:DataTypes.STRING(100),
        part7_sec1_value2:DataTypes.STRING(100),
        part7_sec1_value3:DataTypes.STRING(100),
        part7_sec2_value1:DataTypes.STRING(100),
        part7_sec2_value2:DataTypes.STRING(100),
        part7_sec2_value3:DataTypes.STRING(100),
        part7_sec3_value1:DataTypes.STRING(2),
        part7_sec3_value2:DataTypes.STRING(2),
        part7_sec3_value3:DataTypes.STRING(2),
        part7_sec3_value4:DataTypes.STRING(2),
        part7_sec3_value5:DataTypes.STRING(2),
        part7_sec3_comment1:DataTypes.STRING(100),
        part7_sec4_comment1:DataTypes.STRING(100),
        part7_sec4_comment2:DataTypes.STRING(100),
        part7_sec4_comment3:DataTypes.STRING(100),
        part7_sec4_comment4:DataTypes.STRING(100),
        part7_sec4_value1:DataTypes.STRING(2),
        part7_sec4_value2:DataTypes.STRING(2),
        PATIENT_SIGN:DataTypes.TEXT,
        PATIENT_SIGN1:DataTypes.TEXT,
        PATIENT_SIGN2:DataTypes.TEXT,
        PATIENT_SIGN3:DataTypes.TEXT,
        PATIENT_SIGN4:DataTypes.TEXT,
        PATIENT_SIGN5:DataTypes.TEXT,
        dateChose:DataTypes.DATE,
        dateChose1:DataTypes.DATE
      
    },{
        tableName: 'pemedical_doc', // đặt tên bảng
        createdAt: 'Creation_date',
        updatedAt: 'Last_update_date'
    });

    return pemedical_doc;
};