angular.module('app.loggedIn.problem')
.config(function($stateProvider){
    $stateProvider
        .state("loggedIn.patient.problem_list",{
            url:'/problem',
            views:{
                'main-content':{
                    templateUrl:"modules/problem/views/list.html",
                    controller:"ProblemListController"
                }
            }
        })
})